OrdererOrgs:

  - Name: Orderer
    Domain: fabric.com

    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: org1
    Domain: org1.fabric.com

    Template:
      Count: 2

    Users:
      Count: 3